### ISSUE TITLE
Adding VLAN does not work

### ISSUE THREAD

**Issue by andusvan** [Dell-Networking/ansible-role-dellos-vlan#28]
I'm trying to add an VLAN to an interface, which does not have any VLANs set. But it does not work.

**What I'm using:**
- N3048EP-ON with 6.5.2.35 (N3000Advv6.5.2.35)
- ansible 2.9.7
- Dell-Networking.dellos-vlan v3.2.0-beta.2
 ``` /root/.ansible/roles/Dell-Networking.dellos-vlan/meta/.galaxy_install_info
   {install_date: 'Thu Jun 18 08:09:15 2020', version: v3.2.0-beta.2}
```

At the beginning the switch does not have any vlans on the port to configure.

This config files:
> inventory.yaml
```
[dellos6]
dellos6_sw1 ansible_host=10.10.129.240
```
> setvlan_os6.yaml
```
---
- hosts: dellos6
  connection: network_cli
  roles:
    - Dell-Networking.dellos-vlan
```

> host_vars/dellos6_sw1.yaml
``` 
hostname: dellos6_sw1

ansible_become: yes
ansible_ssh_user: admin
ansible_ssh_pass: secret
ansible_network_os: dellos6
build_dir: /root/dell/temp/
dellos_cfg_generate: yes

dellos_vlan:
  #default_vlan: true
  vlan 111:
     name: "GUEST"
     tagged_members:
        - port: Gi1/0/20
          state: present
     state: present
```

**This is what I got:**

> ansible-playbook -i inventory.yaml setvlan_os6.yaml -vv
```
ansible-playbook 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: setvlan_os6.yaml *************************************************************************************
1 plays in setvlan_os6.yaml

PLAY [dellos6] *************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************
task path: /root/dell/ansible-dellos-examples-3.0.0/setvlan_os6.yaml:2
ok: [dellos6_sw1]
META: ran handlers

TASK [Dell-Networking.dellos-vlan : Provision dellos6 tasks] ***************************************************
task path: /root/.ansible/roles/Dell-Networking.dellos-vlan/tasks/main.yml:3
included: /root/.ansible/roles/Dell-Networking.dellos-vlan/tasks/provision_dellos6.yaml for dellos6_sw1

TASK [Dell-Networking.dellos-vlan : Generating VLAN configuration for dellos6] *********************************
task path: /root/.ansible/roles/Dell-Networking.dellos-vlan/tasks/provision_dellos6.yaml:3
ok: [dellos6_sw1] => {"changed": false, "checksum": "7f21e34ae29519ff76b840fd2e2a00f2dadba331", "dest": "/root/dell/temp//vlan6_dellos6_sw1.conf.part", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/root/dell/temp//vlan6_dellos6_sw1.conf.part", "size": 91, "state": "file", "uid": 0}

TASK [Dell-Networking.dellos-vlan : Provisioning VLAN configuration for dellos6] *******************************
task path: /root/.ansible/roles/Dell-Networking.dellos-vlan/tasks/provision_dellos6.yaml:11
changed: [dellos6_sw1] => {"changed": true, "commands": ["interface Gi1/0/20", "switchport trunk allowed vlan add 111", "exit"], "saved": false, "updates": ["interface Gi1/0/20", "switchport trunk allowed vlan add 111", "exit"]}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************
dellos6_sw1                : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Running the playbook results in "ok" (and correct "changed" entry), but nothing happens on the switch...

**Analysis:**

In the output of the TASK (see above) the following commands are generated:
```
  interface Gi1/0/20 
  switchport trunk allowed vlan add 111
  exit
```

If I run the command in the switch's console, the command is accepted, but nothing happend either.
But, if I run the following command instead:
``` switchport trunk allowed vlan 111```
it works as expected.

**Questions:**

1. What I'm doing wrong? Or is this a bug?
2. What do I have to specfiy, if I want to configure VLANs in "general" mode?
