### ISSUE TITLE
role does not work for properly with ansible >=2.10

### ISSUE THREAD

**Issue by bodik** [Dell-Networking/ansible-role-dellos-vlan#29]
turns out that simplest usage fails since ansible 2.10. the issue is that `src` parameter is not used as template path but rather a command string itself

playbook
```
---
- name: config X
  hosts: all
  gather_facts: false
  vars:
    dellos_cfg_generate: true
    build_dir: tmp
    hostname: "{{ inventory_hostname }}"
   
    dellos_vlan:
        VLAN 10:
          name: "vlan wan"
          state: present
   
  roles:
    - dell-networking.dellos-vlan
```

output
```
TASK [dell-networking.dellos-vlan : Provisioning VLAN configuration for dellos9] ***********************************************************************************************************************************
fatal: [XXX]: FAILED! => {"changed": false, "command": "dellos9_vlan.j2", "msg": "dellos9_vlan.j2\r\n                           ^\r\n% Error: Invalid input at \"^\" marker.\r\nXXX(conf)#", "rc": -32603}
```
